[package]
edition.workspace = true
name = "gravity-types"
repository.workspace = true
version.workspace = true

[dependencies]
agave-scheduler-bindings.workspace = true
anyhow.workspace = true
backtrace.workspace = true
bs58.workspace = true
clickhouse.workspace = true
const-hex.workspace = true
dotenvy.workspace = true
flux.workspace = true
rand.workspace = true
reqwest.workspace = true
rts-alloc.workspace = true
rustc-hash.workspace = true
serde.workspace = true
serde_ignored.workspace = true
serde_path_to_error.workspace = true
serde_repr.workspace = true
gravity-protos.workspace = true
opentelemetry.workspace = true
opentelemetry-appender-tracing.workspace = true
opentelemetry-otlp.workspace = true
opentelemetry_sdk.workspace = true
solana-address.workspace = true
solana-keypair.workspace = true
solana-message.workspace = true
solana-signature.workspace = true
solana-signer.workspace = true
thiserror.workspace = true
tokio.workspace = true
toml.workspace = true
tonic.workspace = true
tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true
url.workspace = true
uuid.workspace = true
wincode.workspace = true
wincode-derive.workspace = true

[lints]
workspace = true

[dev-dependencies]
anyhow.workspace = true
solana-transaction = { workspace = true, features = ["wincode"] }
solana-wincode = { package = "wincode", version = "0.6" }
tempfile.workspace = true
